### ISSUE TITLE
Not working with Complex Numbers?

### ISSUE THREAD

**Issue by j1ver** [flatironinstitute/sparse_dot#18]
Seems not to work with complex numbers, is this correct?

**Comment by asistradition** [comment]
Currently that is correct. There's no reason that it couldn't be done; the numpy complex dtypes look like they're aligned the same as the MKL_Complex C structs, so I think it would be pretty quick to add complex support. I just haven't done it because I didn't need it.

If it's something that would be useful I can add it to the to-do list.

**Comment by j1ver** [comment]
Okay thanks for the fast reply!
Unfourtunately, I dont know anything/much about the MKL structs so I cannot do it myself.

But yes, it would be super useful for Quantum Mechanics. The time evolution and mostly anthing else is manifest complex

**Comment by j1ver** [comment]
Currently I am just using that the matrix can be expressed as m=a+i b and then use the cast=True flag and then use
m*H+i (-i m)*H

**Comment by asistradition** [comment]
Aight, I'll take at getting it going natively. It should be pretty easy - might take a bit to make sure there's good test coverage.

**Comment by j1ver** [comment]
Thank you very much.

**Comment by asistradition** [comment]
Aight, this should support complex floats (`np.csingle` and `np.cdouble`) for matrix multiplication now. 

Let me know if there's any problems - I think the tests are pretty comprehensive, but there's always some weird edge condition I forgot.
