### ISSUE TITLE
MKL 2022.1.0 version with conda setup not working

### ISSUE THREAD

**Issue by DManowitz** [flatironinstitute/sparse_dot#20]
Looks like a similar problem to issue #15.  They've changed the name of the library again, this time to mkl_rt.2.dll.

**Comment by asistradition** [comment]
Fixed in a6eb5085f262f164e67b0accca0e70f5bdd0abaa by searching for any of mkl_rt.{i}.dll where i is between 5 and 1. That should buy me a couple years. Released on pypi as v0.8.2

I don't have a CI or testing environment for windows so I'm going to leave this issue open for a few days in case there are any more problems.
